import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AnimatedBubbleParticles } from "@/components/lightswind/animated-bubble-particles";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
                <div className="min-h-screen bg-[#fefcff] w-full relative">
                    {/* Aurora Dream Corner Whispers */}
                    <div
                        className="absolute inset-0 z-0"
                        style={{
                            backgroundImage: `
                            radial-gradient(circle at 30% 70%, rgba(173, 216, 230, 0.35), transparent 60%),
                            radial-gradient(circle at 70% 30%, rgba(255, 182, 193, 0.4), transparent 60%)`,
                        }}
                    />
                    {/* Your content goes here */}
                    <AnimatedBubbleParticles particleColor="#ffd6e8" backgroundColor="transparent">
                        <div className="w-full backdrop-blur-lg">{children}</div>
                    </AnimatedBubbleParticles>
                </div>
            </body>
        </html>
    );
}
