import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AnimatedBubbleParticles from "@/components/lightswind/animated-bubble-particles";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
                <div className="min-h-screen bg-[#fefcff] w-full relative">
                    {/* Aurora Dream Corner Whispers */}
                    <div
                        className="absolute inset-0 z-0"
                        style={{
                            backgroundImage: `
                            radial-gradient(circle at 30% 70%, rgba(173, 216, 230, 0.35), transparent 60%),
                            radial-gradient(circle at 70% 30%, rgba(255, 182, 193, 0.4), transparent 60%)`,
                        }}
                    />
                    {/* Your content goes here */}
                    <AnimatedBubbleParticles
                        particleColor={[
                            "#FFB6C1", // pastel pink (same as background pink)
                            "#FFDAB9", // peach / soft orange
                            "#FFFACD", // light lemon
                            "#E6E6FA", // lavender
                        ]}
                    >
                        <div className="w-full  backdrop-blur-xl animated-background">
                            {/* Floating blurred circles */}
                            <div className="circle w-40 h-40 bg-white/10 !animate-[float1_18s_linear_infinite] bg-gradient-to-r from-pink-500 via-yellow-500 to-green-500 bg-[length:400%_400%] " />
                            <div className="circle w-32 h-32 bg-white/15 animate-[float2_25s_linear_infinite] bg-gradient-to-r from-pink-500 via-yellow-500 to-green-500 bg-[length:400%_400%] " />
                            <div className="circle w-48 h-48 bg-white/10 animate-[float3_10s_linear_infinite] bg-gradient-to-r from-pink-500 via-yellow-500 to-green-500 bg-[length:400%_400%] " />
                            <div className="circle w-36 h-36 bg-white/20 animate-[float4_40s_linear_infinite] bg-gradient-to-r from-pink-500 via-yellow-500 to-green-500 bg-[length:400%_400%] " />
                            {children}
                        </div>
                    </AnimatedBubbleParticles>
                </div>
            </body>
        </html>
    );
}
